Aditya Aggarwal 18803011 B13

In [1]:
import numpy as np 

In [2]:
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [3]:
Z = np.arange(50) 
Z = Z[::-1] 
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


In [4]:
Z = np.arange(9).reshape(3,3) 
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [5]:
nz = np.nonzero([1,2,0,0,4,0]) 
print(nz)

(array([0, 1, 4], dtype=int64),)


In [6]:
Z = np.eye(3) 
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [7]:
Z = np.random.random((10,10)) *10
Zmin, Zmax = Z.min(), Z.max() 
print(Z)
print(Zmin, Zmax) 

[[1.11631972e+00 1.90763477e+00 4.86501812e-01 2.03064057e+00
  5.61528568e+00 2.83326983e+00 4.45666655e+00 3.78741600e-01
  8.88381771e+00 8.95398446e+00]
 [2.63547653e+00 1.13691094e+00 3.93641412e+00 6.49104403e-01
  3.14785182e+00 5.77019269e+00 8.80600776e+00 9.59822381e+00
  1.56488028e+00 6.93323759e+00]
 [2.68183621e+00 8.88560155e-01 4.88217868e+00 4.98116825e+00
  7.45374156e+00 1.42445694e-01 6.40429465e+00 1.39830120e+00
  8.12915231e+00 8.81174814e+00]
 [3.20499526e+00 2.71522632e-01 6.49671988e+00 3.51792986e+00
  2.79290889e+00 7.94156708e+00 4.43581183e+00 7.20985773e+00
  7.36525132e+00 8.35524133e+00]
 [8.75902723e+00 7.78159019e-01 9.26694928e+00 7.10329034e+00
  7.74329292e+00 5.80106537e+00 3.21411242e+00 7.80523178e+00
  8.94869370e+00 2.46844479e+00]
 [5.70887294e+00 7.13525837e+00 1.69598493e+00 6.81033106e+00
  6.58496583e+00 2.46804925e+00 5.60894237e+00 8.19765130e+00
  9.34219407e+00 4.42059430e+00]
 [2.85625952e+00 6.30470204e+00 4.31898259e+00 9.96788160e

In [8]:
Z = np.random.random(30) *10
m = Z.mean()
print(Z)
print(m) 


[6.67089407 7.1876902  7.9663225  9.99304946 6.45835364 4.10905047
 1.70859861 5.55231752 1.32079781 0.27687348 8.17855041 5.03847817
 0.67605257 7.56128428 2.58244492 8.43804561 4.1387201  3.02604848
 1.2248509  1.79252959 6.50590429 9.31172098 3.13998632 1.95088922
 2.85038293 1.93230272 5.85191226 4.17259052 5.13293057 1.59926574]
4.544961277669169


In [9]:
Z = np.ones((10,10)) 
Z[1:-1,1:-1] = 0 
print(Z) 


[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [10]:
Z = np.ones((5,5)) 
Z = np.pad(Z, pad_width=1, mode='constant',  
constant_values=0) 
print(Z) 


[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [11]:
Z = np.dot(np.ones((5,3)), np.ones((3,2))) 
print(Z) 


[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [12]:
Z = np.arange(11) 
Z[(3 < Z) & (Z <= 8)] *= -1 
print(Z) 


[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


In [13]:
Z1 = np.random.randint(0,10,10) 
Z2 = np.random.randint(0,10,10) 
print(np.intersect1d(Z1,Z2)) 


[1 4 8]


In [14]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D') 
print(yesterday)
today = np.datetime64('today', 'D') 
print(today)
tomorrow = np.datetime64('today', 'D') + np.timedelta64(1, 'D') 
print(tomorrow)

2021-06-06
2021-06-07
2021-06-08


In [15]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]') 
print(Z) 


['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [16]:
A = np.random.randint(0,2,5) 
B = np.random.randint(0,2,5)  
print(A)
print(B)
equal = np.allclose(A,B) 
print(equal) 
equal = np.array_equal(A,B) 
print(equal) 


[0 0 0 1 1]
[0 0 1 1 1]
False
False


In [17]:
Z = np.random.random(10) 
print(Z)
Z[Z.argmax()] = 0
print(Z)

[0.77460634 0.66215547 0.72178612 0.35267552 0.36744002 0.45847738
 0.38238093 0.58355993 0.25022149 0.91089269]
[0.77460634 0.66215547 0.72178612 0.35267552 0.36744002 0.45847738
 0.38238093 0.58355993 0.25022149 0.        ]


# Practice Questions

In [18]:
#Q1
print(np.__version__)
x = np.array([1,1,1,2,2,2,5,25,1,1])
unique, counts = np.unique(x, return_counts=True)
print (np.asarray((unique, counts)).T)

1.19.2
[[ 1  5]
 [ 2  3]
 [ 5  1]
 [25  1]]


In [19]:
#Q2
s= "11100110010"
a=np.char.count(s,'1')
x=np.ones(len(s))
x[a:]=0
print(x)

[1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0.]


In [20]:
#Q3
index=2
s="dslglerhe"
s=s[:index]+s[index+1:]
print(s)

dsglerhe


In [21]:
#Q4
Z = np.ones((3,3))
print(Z)
Z = np.pad(Z, pad_width=1, mode='constant',  
constant_values=0) 
print(Z) 

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [22]:
#Q5
a=[ 0, 10, 20, 40, 60] 
b=[0,40]
print(np.isin(a,b))

[ True False False  True False]


In [23]:
#Q6
arr1=[ 0, 10, 20, 40, 60, 80]
arr2=[10, 30, 40, 50, 70]  
print(np.setxor1d(arr1, arr2))

[ 0 20 30 50 60 70 80]


In [24]:
#Q7
a = np.array([1, 2, 3])
b = np.array([2, 3, 4])
print(np.column_stack((a,b)))

[[1 2]
 [2 3]
 [3 4]]


In [25]:
#Q8
a = np.arange(4).reshape((2,2))
print(a)
print(np.trace(a))
print(np.linalg.det(a))
print(np.linalg.matrix_rank(a))

[[0 1]
 [2 3]]
3
-2.0
2
